import { ruleTester } from '../../tests/ruleTester.ts';
import { typePlacementRule } from './typePlacement.ts';

const lines = (...text: string[]) => `${text.join('\n')}\n`;

ruleTester.run('type-placement', typePlacementRule, {
  valid: [
    lines(
      "import { home } from './home.ts';",
      '',
      'type Paths = string[];',
      '',
      'export const paths: Paths = [home];',
    ),
    lines(
      "export { home } from './home.ts';",
      '',
      'const defaults = { path: 1 };',
      '',
      'export type Defaults = typeof defaults;',
      '',
      'const build = (path: string) => ({ path });',
      '',
      'export type Built = ReturnType<typeof build>;',
    ),
  ],
  invalid: [
    {
      code: lines(
        "import { home } from './home.ts';",
        '',
        'export const root = home.trim();',
        '',
        '// Describes one request.',
        'export interface Request {',
        '  path: string;',
        '}',
        '',
        'const defaults = { path: root };',
        '',
        'export type Defaults = typeof defaults;',
        '',
        'const build = (path: string): Request => ({ path });',
        '',
        'export type Built = ReturnType<typeof build>;',
        '',
        'type Paths = string[];',
        '',
        'export const paths: Paths = [build(root).path, defaults.path];',
        '',
        'type Name = string; paths.push(root);',
        '',
        'export default interface Options {',
        '  name: Name;',
        '}',
        '',
        'paths.pop(); export type Label = Name;',
      ),
      errors: [
        {
          messageId: 'placement',
          data: { names: 'Request", "Paths", "Name", "Options", "Label' },
          line: 6,
        },
      ],
      // The style command formats after fixing, which removes the extra blank lines.
      output: [
        "import { home } from './home.ts';",
        '',
        '// Describes one request.',
        'export interface Request {',
        '  path: string;',
        '}',
        '',
        'type Paths = string[];',
        '',
        'type Name = string;',
        '',
        'export default interface Options {',
        '  name: Name;',
        '}',
        '',
        'export type Label = Name;',
        '',
        'export const root = home.trim();',
        '',
        '',
        'const defaults = { path: root };',
        '',
        'export type Defaults = typeof defaults;',
        '',
        'const build = (path: string): Request => ({ path });',
        '',
        'export type Built = ReturnType<typeof build>;',
        '',
        '',
        'export const paths: Paths = [build(root).path, defaults.path];',
        '',
        'paths.push(root);',
        '',
        '',
        'paths.pop(); ',
      ].join('\n'),
    },
    {
      code: lines(
        'export const count = 1;',
        '',
        'type Label = string; /* This comment',
        '   continues on a second line. */',
        '',
        "export const label: Label = 'ready';",
      ),
      errors: [{ messageId: 'placement', data: { names: 'Label' }, line: 3 }],
      // A block comment that trails the type moves whole, so no value ends up inside it.
      output: lines(
        'type Label = string; /* This comment',
        '   continues on a second line. */',
        '',
        'export const count = 1;',
        '',
        '',
        "export const label: Label = 'ready';",
      ),
    },
    {
      code: lines(
        'export const count = 1; /* Trails the value',
        '   and ends beside the type. */ type Label = string;',
        '',
        "export const label: Label = 'ready';",
      ),
      errors: [{ messageId: 'placement', data: { names: 'Label' }, line: 2 }],
      // The type starts on a line that a comment opened, so it moves from its own start.
      output: lines(
        'type Label = string;',
        '',
        'export const count = 1; /* Trails the value',
        '   and ends beside the type. */ ',
        "export const label: Label = 'ready';",
      ),
    },
    {
      code: lines(
        'export const count = 1;',
        '',
        'type First = string; /* first',
        ' */ /* second */',
        'type Second = number;',
        '',
        "export const label: First | Second = 'ready';",
      ),
      errors: [{ messageId: 'placement', data: { names: 'First", "Second' }, line: 3 }],
      // Each comment moves with exactly one type, so the two moved ranges never overlap.
      output: lines(
        'type First = string; /* first',
        ' */ /* second */',
        '',
        'type Second = number;',
        '',
        'export const count = 1;',
        '',
        '',
        "export const label: First | Second = 'ready';",
      ),
    },
  ],
});
